(() => {
  const lesson = document.body.dataset.lesson;
  const C = {ink:'#1f2f3d', muted:'#647582', grid:'#dbe4e8', blue:'#3c78a8', red:'#c74d58', teal:'#31776f'};
  let seed = lesson === 'polynomial' ? 6047 : 9061;
  const $ = id => document.getElementById(id);
  const mean = a => a.reduce((s,v) => s + v, 0) / a.length;
  const sum = a => a.reduce((s,v) => s + v, 0);
  function rng(){ seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; }
  function normal(){ let u = 0, v = 0; while(!u)u=rng(); while(!v)v=rng(); return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v); }
  function solve(A,b){ const n=b.length, m=A.map((r,i)=>[...r,b[i]]); for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(m[r][c])>Math.abs(m[p][c]))p=r;[m[c],m[p]]=[m[p],m[c]];const d=m[c][c];for(let j=c;j<=n;j++)m[c][j]/=d;for(let r=0;r<n;r++)if(r!==c){const f=m[r][c];for(let j=c;j<=n;j++)m[r][j]-=f*m[c][j];}} return m.map(r=>r[n]); }
  function fit(data, degree, transform = y => y){ const p=degree+1,A=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0); data.forEach(d=>{const z=transform(d.y),v=Array.from({length:p},(_,i)=>d.x**i);for(let i=0;i<p;i++){b[i]+=v[i]*z;for(let j=0;j<p;j++)A[i][j]+=v[i]*v[j];}});const coef=solve(A,b), predict=x=>sum(coef.map((c,i)=>c*x**i)),res=data.map(d=>transform(d.y)-predict(d.x)),sigma=Math.sqrt(sum(res.map(v=>v*v))/(data.length-p));return {coef,predict,res,sigma,degree,transform}; }
  function invNorm(p){ const a=[-39.6968302866538,220.946098424521,-275.928510446969,138.357751867269,-30.6647980661472,2.50662827745924],b=[-54.4760987982241,161.585836858041,-155.698979859887,66.8013118877197,-13.2806815528857],c=[-.00778489400243029,-.322396458041136,-2.40075827716184,-2.54973253934373,4.37466414146497,2.93816398269878],d=[.00778469570904146,.32246712907004,2.445134137143,3.75440866190742]; let q,r;if(p<.02425){q=Math.sqrt(-2*Math.log(p));return (((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1);}if(p>0.97575){q=Math.sqrt(-2*Math.log(1-p));return -(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1);}q=p-.5;r=q*q;return (((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q/(((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1); }
  function svg(id){const s=$(id);s.innerHTML='';const v=s.viewBox.baseVal;return {s,w:v.width,h:v.height};}
  const esc = x => String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;');
  function el(s,name,attrs={},text){const e=document.createElementNS('http://www.w3.org/2000/svg',name);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;s.appendChild(e);return e;}
  const scale=(d0,d1,r0,r1)=>v=>r0+(v-d0)*(r1-r0)/(d1-d0);
  function extent(values,pad=.08){let lo=Math.min(...values),hi=Math.max(...values),p=(hi-lo||1)*pad;return [lo-p,hi+p];}
  function axes(s,w,h,m,xd,yd,xlab,ylab){const x=scale(xd[0],xd[1],m.l,w-m.r),y=scale(yd[0],yd[1],h-m.b,m.t);for(let i=0;i<=4;i++){const xv=xd[0]+i*(xd[1]-xd[0])/4,yv=yd[0]+i*(yd[1]-yd[0])/4;el(s,'line',{x1:x(xv),y1:m.t,x2:x(xv),y2:h-m.b,stroke:C.grid,'stroke-width':.8});el(s,'line',{x1:m.l,y1:y(yv),x2:w-m.r,y2:y(yv),stroke:C.grid,'stroke-width':.8});el(s,'text',{x:x(xv),y:h-m.b+14,'text-anchor':'middle',fill:C.muted,'font-size':8},Number(xv.toFixed(Math.abs(xd[1]-xd[0])<10?1:0)));el(s,'text',{x:m.l-5,y:y(yv)+3,'text-anchor':'end',fill:C.muted,'font-size':8},Number(yv.toFixed(Math.abs(yd[1]-yd[0])<10?1:0)));}el(s,'line',{x1:m.l,y1:h-m.b,x2:w-m.r,y2:h-m.b,stroke:C.ink});el(s,'line',{x1:m.l,y1:m.t,x2:m.l,y2:h-m.b,stroke:C.ink});el(s,'text',{x:(m.l+w-m.r)/2,y:h-4,'text-anchor':'middle',fill:C.muted,'font-size':8},xlab);el(s,'text',{transform:`translate(10 ${(m.t+h-m.b)/2}) rotate(-90)`,'text-anchor':'middle',fill:C.muted,'font-size':8},ylab);return{x,y};}
  function path(s,pts,attrs){el(s,'path',{d:pts.map((p,i)=>`${i?'L':'M'}${p[0].toFixed(2)},${p[1].toFixed(2)}`).join(' '),fill:'none',...attrs});}
  function modelPlot(data, first, second, isLog, xLabel, yLabel){const {s,w,h}=svg('fitPlot'),m={l:52,r:16,t:13,b:38},xd=[0,12],yd=extent(data.map(d=>d.y),.18),a=axes(s,w,h,m,xd,yd,xLabel,yLabel);data.forEach(d=>el(s,'circle',{cx:a.x(d.x),cy:a.y(d.y),r:3.2,fill:C.blue,'fill-opacity':.65}));const xs=Array.from({length:121},(_,i)=>i/10);path(s,xs.map(x=>[a.x(x),a.y(first.predict(x))]),{stroke:C.red,'stroke-width':2.3});path(s,xs.map(x=>[a.x(x),a.y(isLog?Math.exp(second.predict(x)):second.predict(x))]),{stroke:C.teal,'stroke-width':2.5});}
  function residualPlot(id, data, model, transformLabel){const {s,w,h}=svg(id),m={l:37,r:7,t:9,b:31},pts=data.map((d,i)=>({fit:model.predict(d.x),r:model.res[i]/model.sigma})),xd=extent(pts.map(d=>d.fit)),yd=extent(pts.map(d=>d.r),.14),a=axes(s,w,h,m,xd,yd,'Fitted',transformLabel);el(s,'line',{x1:m.l,x2:w-m.r,y1:a.y(0),y2:a.y(0),stroke:C.ink,'stroke-dasharray':'3 3'});pts.forEach(d=>el(s,'circle',{cx:a.x(d.fit),cy:a.y(d.r),r:2.1,fill:'#fff',stroke:C.blue,'stroke-width':.9}));}
  function qqPlot(id, model){const {s,w,h}=svg(id),m={l:37,r:7,t:9,b:31},vals=model.res.map(v=>v/model.sigma).sort((a,b)=>a-b),theory=vals.map((_,i)=>invNorm((i+.5)/vals.length)),yd=extent(vals,.15),a=axes(s,w,h,m,[-2.3,2.3],yd,'Normal q','Residual q');const q1=Math.floor(vals.length*.25),q3=Math.floor(vals.length*.75),sl=(vals[q3]-vals[q1])/(theory[q3]-theory[q1]),ic=vals[q1]-sl*theory[q1];el(s,'line',{x1:a.x(-2.3),y1:a.y(ic-2.3*sl),x2:a.x(2.3),y2:a.y(ic+2.3*sl),stroke:C.red,'stroke-width':1.2,'stroke-dasharray':'4 3'});vals.forEach((v,i)=>el(s,'circle',{cx:a.x(theory[i]),cy:a.y(v),r:1.9,fill:'#fff',stroke:C.blue,'stroke-width':.8}));}
  function scalePlot(id,data,model){const {s,w,h}=svg(id),m={l:37,r:7,t:9,b:31},pts=data.map((d,i)=>({fit:model.predict(d.x),v:Math.sqrt(Math.abs(model.res[i]/model.sigma))})),xd=extent(pts.map(d=>d.fit)),yd=[0,Math.max(1.8,...pts.map(d=>d.v))],a=axes(s,w,h,m,xd,yd,'Fitted','√|resid.|');pts.forEach(d=>el(s,'circle',{cx:a.x(d.fit),cy:a.y(d.v),r:2.1,fill:'#fff',stroke:C.blue,'stroke-width':.9}));const ordered=[...pts].sort((a,b)=>a.fit-b.fit),groups=[ordered.slice(0,Math.ceil(ordered.length/3)),ordered.slice(Math.ceil(ordered.length/3),Math.ceil(2*ordered.length/3)),ordered.slice(Math.ceil(2*ordered.length/3))];path(s,groups.map(g=>[a.x(mean(g.map(d=>d.fit))),a.y(mean(g.map(d=>d.v)))]),{stroke:C.red,'stroke-width':1.4});}
  function metric(id,data,model,label){const tss=sum(data.map(d=>((model.transform(d.y)-mean(data.map(q=>model.transform(q.y))))**2))),rss=sum(model.res.map(v=>v*v)),r2=1-rss/tss;$(id).innerHTML=`<span><b>Residual SE:</b> ${model.sigma.toFixed(2)} ${esc(label)}</span><span><b>R²:</b> ${(100*r2).toFixed(0)}%</span>`;}
  function makePolynomial(){return Array.from({length:42},(_,i)=>{const x=.3+11.3*rng(),y=10+4.3*x-.34*x*x+normal()*2.25;return{x,y};});}
  function makeLog(){return Array.from({length:42},()=>{const x=.3+11.3*rng(),logY=2.12+.145*x+normal()*.22;return{x,y:Math.exp(logY)};});}
  const overfitData=[.2,.8,1.4,2.3,3.5,4,5.1,5.8,6.6,7.2,8.1,9,9.6,10.4,11.2,11.7].map((x,i)=>({x,y:9+4*x-.32*x*x+[-1.2,.5,-1.7,.8,1.4,-.6,1.9,-1.8,1.1,-1.3,1.7,-1.4,.8,-2,1.7,-.5][i]}));
  const quadraticTruth = x => 9+4*x-.32*x*x;
  function fitScaledPolynomial(data,degree){const p=degree+1,A=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0),z=x=>(x-6)/6;data.forEach(d=>{const v=Array.from({length:p},(_,i)=>z(d.x)**i);for(let i=0;i<p;i++){b[i]+=v[i]*d.y;for(let j=0;j<p;j++)A[i][j]+=v[i]*v[j];}});const coef=solve(A,b),predict=x=>sum(coef.map((c,i)=>c*z(x)**i));return{predict,res:data.map(d=>d.y-predict(d.x))};}
  const rmse=(data,predict)=>Math.sqrt(mean(data.map(d=>(d.y-predict(d.x))**2)));
  function renderOverfit(degree){const model=fitScaledPolynomial(overfitData,degree),test=Array.from({length:121},(_,i)=>({x:i/10,y:quadraticTruth(i/10)})),{s,w,h}=svg('overfit-plot'),m={l:52,r:16,t:13,b:38},curveXs=Array.from({length:241},(_,i)=>i/20),allY=[...overfitData.map(d=>d.y),...curveXs.map(quadraticTruth),...curveXs.map(model.predict)],yd=extent(allY,.1),a=axes(s,w,h,m,[0,12],yd,'Coaching meetings','Weekly sales ($000)');path(s,curveXs.map(x=>[a.x(x),a.y(quadraticTruth(x))]),{stroke:C.teal,'stroke-width':1.8,'stroke-dasharray':'6 4'});path(s,curveXs.map(x=>[a.x(x),a.y(model.predict(x))]),{stroke:'#8070a4','stroke-width':2.5});overfitData.forEach(d=>el(s,'circle',{cx:a.x(d.x),cy:a.y(d.y),r:3.3,fill:C.blue,'fill-opacity':.7}));const train=rmse(overfitData,model.predict),testScore=rmse(test,model.predict),isOverfit=degree>=8&&testScore>.5;$('order-value').textContent=`Degree ${degree}`;$('order-down').disabled=degree===1;$('order-up').disabled=degree===9;$('overfit-metrics').innerHTML=`<span><b>Training RMSE:</b> ${train.toFixed(2)}</span><span><b>New-case RMSE:</b> ${testScore.toFixed(2)}</span>${isOverfit?'<span class="warning"><b>Warning:</b> the extra bends fit noise, not the quadratic pattern.</span>':'<span><b>Read it:</b> compare training and new-case error before adding more terms.</span>'}`;}
  function setupOverfit(){let degree=1;const draw=()=>renderOverfit(degree);$('order-down').addEventListener('click',()=>{degree=Math.max(1,degree-1);draw();});$('order-up').addEventListener('click',()=>{degree=Math.min(9,degree+1);draw();});draw();}
  function renderPolynomial(){const data=makePolynomial(),linear=fit(data,1),quad=fit(data,2);modelPlot(data,linear,quad,false,'Coaching meetings','Weekly sales ($000)');[['linear',linear],['quad',quad]].forEach(([name,model])=>{residualPlot(`${name}-rvf`,data,model,'Std. resid.');qqPlot(`${name}-qq`,model);scalePlot(`${name}-sl`,data,model);metric(`${name}-metrics`,data,model,'sales');});}
  function renderLog(){const data=makeLog(),raw=fit(data,1),logged=fit(data,1,Math.log);modelPlot(data,raw,logged,true,'Product demonstrations','Weekly revenue ($000)');[['raw',raw,'revenue'],['log',logged,'log revenue']].forEach(([name,model,label])=>{residualPlot(`${name}-rvf`,data,model,'Std. resid.');qqPlot(`${name}-qq`,model);scalePlot(`${name}-sl`,data,model);metric(`${name}-metrics`,data,model,label);});}
  function render(){lesson==='polynomial'?renderPolynomial():renderLog();}
  $('reroll').addEventListener('click',render);render();if(lesson==='polynomial')setupOverfit();
})();
